openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /alerts/:
    get:
      tags:
      - alerts
      summary: Get Alerts
      operationId: get_alerts_alerts__get
      parameters:
      - name: kind
        in: query
        required: false
        schema:
          anyOf:
          - $ref: '#/components/schemas/AlertKind'
          - type: 'null'
          title: Kind
      - name: ack
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Ack
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertOut'
                title: Response Get Alerts Alerts  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - alerts
      summary: Post Alert
      operationId: post_alert_alerts__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertCreate'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /alerts/{alert_id}/ack:
    post:
      tags:
      - alerts
      summary: Post Alert Ack
      operationId: post_alert_ack_alerts__alert_id__ack_post
      parameters:
      - name: alert_id
        in: path
        required: true
        schema:
          type: integer
          title: Alert Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertAckOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /consumptions/:
    get:
      tags:
      - consumptions
      summary: Get Consumptions
      operationId: get_consumptions_consumptions__get
      parameters:
      - name: product_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Product Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConsumptionOut'
                title: Response Get Consumptions Consumptions  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - consumptions
      summary: Post Consumption
      operationId: post_consumption_consumptions__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsumptionCreate'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumptionOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    AlertAckOut:
      properties:
        id:
          type: integer
          title: Id
        is_ack:
          type: boolean
          title: Is Ack
      type: object
      required:
      - id
      - is_ack
      title: AlertAckOut
    AlertCreate:
      properties:
        product_id:
          type: integer
          exclusiveMinimum: 0.0
          title: Product Id
        kind:
          $ref: '#/components/schemas/AlertKind'
        message:
          type: string
          maxLength: 300
          minLength: 1
          title: Message
        due_date:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Due Date
      type: object
      required:
      - product_id
      - kind
      - message
      title: AlertCreate
    AlertKind:
      type: string
      enum:
      - EXPIRED
      - SOON
      - OUT_OF_STOCK
      title: AlertKind
    AlertOut:
      properties:
        id:
          type: integer
          title: Id
        product_id:
          type: integer
          title: Product Id
        kind:
          type: string
          title: Kind
        message:
          type: string
          title: Message
        due_date:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Due Date
        is_ack:
          type: boolean
          title: Is Ack
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          type: string
          format: date-time
          title: Updated At
      type: object
      required:
      - id
      - product_id
      - kind
      - message
      - is_ack
      - created_at
      - updated_at
      title: AlertOut
    ConsumptionCreate:
      properties:
        product_id:
          type: integer
          exclusiveMinimum: 0.0
          title: Product Id
        quantity:
          type: number
          exclusiveMinimum: 0.0
          title: Quantity
        unit:
          type: string
          maxLength: 16
          minLength: 1
          title: Unit
        consumed_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Consumed At
      type: object
      required:
      - product_id
      - quantity
      - unit
      title: ConsumptionCreate
    ConsumptionOut:
      properties:
        id:
          type: integer
          title: Id
        product_id:
          type: integer
          title: Product Id
        quantity:
          type: number
          title: Quantity
        unit:
          type: string
          title: Unit
        consumed_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Consumed At
        created_at:
          type: string
          format: date-time
          title: Created At
      type: object
      required:
      - id
      - product_id
      - quantity
      - unit
      - consumed_at
      - created_at
      title: ConsumptionOut
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
